function [F,M] = ...
    compute_multirotor_FM(vel_bWb, omega_bWb, n_rpm, rho_slugpft3, c, units_ft)
% compute_multirotor_FM - calculate the multirotor forces and moments
%
% DESCRIPTION: 
%   This function calculates the forces and moments generated by the
%   propellers using a simple hover model.
% 
% INPUTS:
%   vel_bWb - body axis translational velocity [ft/s] (Notation: vel_bWb => vel of body wrt wind frame expressed in body frame)
%   omega_bWb - body axis angular velocity [rad/s]
%   n_rpm - np x 1 vector containing propeller speed [rpm]
%   rho_slugpft3, - air density [slug/ft^3]
%   c - structure containing vehicle constants
%
% OUTPUTS:
%   F - body axis forces [lbf]
%   M - body axis moments [ft-lbf]
%
% WRITTEN BY:
%   Benjamin M. Simmons and Michael J. Acheson
%   NASA Langley Research Center
%   Email: benjamin.m.simmons@nasa.gov
%
% HISTORY:
%   26 JUL 2023 - created and debugged, BMS
%   2/11/2025 - Modified by MJA for BAM
%
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
% OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
% MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
% IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
% CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
% TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
% SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
%
%

% Pull out total quantities (body & wind & turbulence)
u_fps = vel_bWb(1)/units_ft; % need to convert these to fps
v_fps = vel_bWb(2)/units_ft;
w_fps = vel_bWb(3)/units_ft;
p_rps = omega_bWb(1); % already in radians per sec..
q_rps = omega_bWb(2);
r_rps = omega_bWb(3);

% number of propellers
np=4;

% propeller speed [rev/s]
n_revps = n_rpm/60;

% initialize propeller forces and moments
Txb_k=zeros(np,1);
Tyb_k=zeros(np,1);
Tzb_k=zeros(np,1);
Qxb_k=zeros(np,1);
Qyb_k=zeros(np,1);
Qzb_k=zeros(np,1);

% initialize propeller thrust and torque in the local propeller flow axes
T_lbf=zeros(np,1);
Q_lbf=zeros(np,1);

% direction of rotation of the propellers (CW=+1, CCW=-1)
%CW=c.prop_dir'; % c.prop_dir(pk);
CW=c.prop_dir; % c.prop_dir(pk);

% thrust and torque coefficient
CT0 = c.CT0;
CQ0 = c.CQ0.*CW*-1;

% Propeller thrust [lbf]
%T_lbf(pk) = CT0 * (rho_slugpft3 * n_revps(pk).^2 * c.prop_diam_ft^4);
T_lbf = CT0.*(rho_slugpft3.* n_revps.^2 .* c.prop_diam_ft.^4);

% Propeller torque [ft-lbf]
%Q_lbf(pk) = CQ0 * (rho_slugpft3 * n_revps(pk).^2 * c.prop_diam_ft^5);
Q_lbf = CQ0 .* (rho_slugpft3 .* n_revps.^2 .* c.prop_diam_ft.^5);

% distance from the current CG location to the propeller locations [ft]
% dxyz=c.prop_locations_ft(pk,:);
% dx_ft=dxyz(1);
% dy_ft=dxyz(2);

% propeller moments at the CG in the aircraft body frame [ft-lbf]
%Qxb_k(pk) = - T_lbf(pk)*dy_ft;
Qxb_k = - T_lbf.*c.prop_locations_ft(:,2);

%Qyb_k(pk) = + T_lbf(pk)*dx_ft ;
Qyb_k = + T_lbf.*c.prop_locations_ft(:,1);

%Qzb_k(pk) = - Q_lbf(pk);
Qzb_k = - Q_lbf;


% propeller forces in the body frame [lbf]
% Txb_k(pk) = 0;
% Tyb_k(pk) = 0;
Txb_k = zeros(np,1);
Tyb_k = zeros(np,1);
%Tzb_k(pk) = -T_lbf(pk);
Tzb_k = -T_lbf;

% total propeller forces and moments in the body frame
X_lbf=sum(Txb_k);
Y_lbf=sum(Tyb_k);
Z_lbf=sum(Tzb_k);
F = [X_lbf; Y_lbf; Z_lbf];

L_ftlbf=sum(Qxb_k);
M_ftlbf=sum(Qyb_k);
N_ftlbf=sum(Qzb_k);
M = [L_ftlbf; M_ftlbf; N_ftlbf];
return