function cellInfo = ForceMomentBus(varargin)
% FORCEMOMENTBUS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false;
numEng=1;
if nargin >= 1
    if islogical(varargin{1}) && varargin{1} == false 
      suppressObject = true;
    end
    if nargin == 2
        numEng=varargin{2};
    end
end 

cellInfo = { ... 
  { ... 
    'BUS_FORCE_MOMENT', ... 
    'BusForceMoment.h', ... 
    '', ... 
    'Exported', ... 
    '-1', {... 
{'Total', 1, 'Bus: BUS_TOTAL_FM', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Aerodynamics', 1, 'Bus: BUS_AERO_FM', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Propulsion', 1, 'Bus: BUS_ENGINE_FM', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'BUS_TOTAL_FM', ... 
    'BusTotalFM.h', ... 
    '', ... 
    'Exported', ... 
    '-1', {... 
{'Force_b', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Moment_b', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'H_b', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Hdot_b', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'BUS_AERO_FM', ... 
    'BusAeroFM.h', ... 
    '', ... 
    'Exported', ... 
    '-1', {... 
{'Force_b', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Moment_b', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'BUS_ENGINE_FM', ... 
    'BusEngineFM.h', ... 
    '', ... 
    'Exported', ... 
    '-1', {... 
{'Force_b', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Moment_b', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'H_b', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Hdot_b', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo);
end 
%FORCEMOMENTBUS Summary of this function goes here
