function cellInfo = SimOutBus(varargin) 
% SIMOUTBUS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BUS_SIM_OUT', ... 
    'BusSimOut.h', ... 
    '', ... 
    'Exported', ... 
    '-1', {... 
{'Env', 1, 'Bus: BUS_ENVIRONMENT', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EOM', 1, 'Bus: BUS_EOM', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'FM', 1, 'Bus: BUS_FORCE_MOMENT', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Traj_Iner', 1, 'Bus: BUS_REF_INPUT_INER', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RefInputs', 1, 'Bus: BUS_REF_INPUT', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EngBus', 1, 'Bus: BUS_PROP_CMD', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EOM_Sensed', 1, 'Bus: BUS_EOM', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Env_Sensed', 1, 'Bus: BUS_ENVIRONMENT', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Bball_Traj_Iner', 1, 'Bus: BUS_REF_INPUT_INER', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
